services:
  web:
    build: .
    command: gunicorn RecipeSearch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=0
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
      POSTGRES_DB: recipe_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
