# Generated by Django 5.1.6 on 2025-03-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_category_id_alter_profile_id_alter_recipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
