# Generated by Django 5.1.7 on 2025-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_userpantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpantry',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
