# Generated by Django 5.1.7 on 2025-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
    ]
