# Generated by Django 5.2 on 2025-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_cook_time_recipe_cuisine_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
